inventories/urls.py
from django.urls import path

from . import views

app_name = 'inventories'

urlpatterns = [
    path('', views.index, name='index'),
    path('base/', views.base, name='base'),

    path('display/desktop', views.display_desktops, name='display_desktop'),
    path('create/desktop/', views.create_desktop, name="create_desktop"),
    path('update/desktop/<int:id>', views.update_desktop, name='update_desktop'),
    path('delete/desktop/<int:id>', views.delete_desktop, name='delete_desktop'),


    path('display/laptop', views.display_laptops, name='display_laptop'),
    path('create/laptop/', views.create_laptop, name="create_laptop"),
    path('update/laptop/<int:id>', views.update_laptop, name='update_laptop'),
    path('delete/laptop/<int:id>', views.delete_laptop, name='delete_laptop'),

    path('display/mobile', views.display_mobiles, name='display_mobile'),
    path('create/mobile/', views.create_mobile, name="create_mobile"),
    path('update/mobile/<int:id>', views.update_mobile, name='update_mobile'),
    path('delete/mobile/<int:id>', views.delete_mobile, name='delete_mobile'),


    path('display/user', views.display_users, name='display_user'),
    path('create/user/', views.create_user, name="create_user"),
    path('update/user/<int:id>', views.update_user, name='update_user'),
    path('delete/user/<int:id>', views.delete_user, name='delete_user'),

]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('inventories/', include('inventories.urls')),
    path('auth/', include('auth_login.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

inventories/models.py
from django.db import models

# Create your models here.


CARGO = (
    ('SUPERVISOR', 'Supervisor'),
    ('ADMINISTRADOR', 'Administrador'),
)


class User(models.Model):
    name = models.CharField(max_length=150)
    age = models.PositiveIntegerField()
    email = models.EmailField()
    rut = models.CharField(max_length=12)
    cargo = models.CharField(choices=CARGO, max_length=13)
    photo = models.ImageField(upload_to='users/', blank=True)

    def __str__(self):
        return self.name


class Desktop(models.Model):
    name = models.CharField(max_length=200, blank=False)
    price = models.IntegerField()
    photo = models.ImageField(upload_to='devices/desktop', blank=True)

    choices = (
        ('DISPONIBLE', 'Item listo para ser vendido'),
        ('VENDIDO', 'Item fue vendido'),
        ('REABASTECIMIENTO', 'Reposición de ítem')
    )

    status = models.CharField(max_length=16, choices=choices, default='VENDIDO')
    issues = models.CharField(max_length=50, default="Sin detalles")

    def __str__(self):
        return 'Type: {0} Price: {1}'.format(self.name, self.price)


class Laptop(models.Model):
    name = models.CharField(max_length=200, blank=False)
    price = models.IntegerField()
    photo = models.ImageField(upload_to='devices/laptop', blank=True)

    choices = (
        ('DISPONIBLE', 'Item listo para ser vendido'),
        ('VENDIDO', 'Item fue vendido'),
        ('REABASTECIMIENTO', 'Reposición de ítem')
    )

    status = models.CharField(max_length=16, choices=choices, default='VENDIDO')
    issues = models.CharField(max_length=50, default="Sin detalles")

    def __str__(self):
        return 'Type: {0} Price: {1}'.format(self.name, self.price)


class Mobile(models.Model):
    name = models.CharField(max_length=200, blank=False)
    price = models.IntegerField()
    photo = models.ImageField(upload_to='devices/mobile', blank=True)

    choices = (
        ('DISPONIBLE', 'Item listo para ser vendido'),
        ('VENDIDO', 'Item fue vendido'),
        ('REABASTECIMIENTO', 'Reposición de ítem')
    )

    status = models.CharField(max_length=16, choices=choices, default='VENDIDO')
    issues = models.CharField(max_length=50, default="Sin detalles")

    def __str__(self):
        return 'Type: {0} Price: {1}'.format(self.name, self.price)

inventories/forms.py
from django import forms
from inventories.models import Desktop, Laptop, Mobile, User


class DesktopForm(forms.ModelForm):
    class Meta:
        model = Desktop
        fields = '__all__'


class LaptopForm(forms.ModelForm):
    class Meta:
        model = Laptop
        fields = '__all__'


class MobileForm(forms.ModelForm):
    class Meta:
        model = Mobile
        fields = '__all__'


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields ='__all__'

inventories/views.py
from django.shortcuts import render, redirect
from django.core.paginator import (Paginator,
                                   EmptyPage,
                                   PageNotAnInteger)
from django.contrib.auth.decorators import (login_required,
                                            permission_required)
from inventories.models import (Desktop,
                                Laptop,
                                Mobile,
                                User)
from inventories.forms import (DesktopForm,
                               LaptopForm,
                               MobileForm,
                               UserForm)

# Create your views here.


@login_required()
def index(request):
    data = {}
    template_name = 'index.html'
    data['items'] = Laptop.objects.all()
    context = {
        'items': data,
        'header': 'Laptops'
    }

    return render(request, template_name, data)


@login_required()
def base(request):
    data = {}
    template_name = 'base.html'

    data['title'] = "Desde la Base"

    return render(request, template_name)


@login_required()
def display_users(request):
    data = {}
    template_name = 'display_users.html'
    data['items'] = User.objects.all()
    context = {
        'items': data,
        'header': 'Users'
    }

    return render(request, template_name, data)


@permission_required('inventories.add_user')
def create_user(request):
    data = {}
    template_name = 'create_user.html'

    data['form'] = UserForm(request.POST or None)

    if data['form'].is_valid():
        data['form'].save()
        return redirect('inventories:display_user')

    return render(request, template_name, data)


@permission_required('inventories.change_user')
def update_user(request, id):
    template_name = 'update_user.html'
    data = {}

    user = User.objects.get(pk=id)
    data['form'] = UserForm(request.POST or None, instance=user)

    if data['form'].is_valid():
        data['form'].save()
        return redirect('inventories:display_user')

    return render(request, template_name, data)


@permission_required('inventories.delete_user')
def delete_user(request, id):
    #data = {}
    user = User.objects.get(pk=id)
    #data['desktop'] = Desktop.objects.get(pk=id)
    #template_name = 'update_mobile.html'
    user.delete()
    #return render(request, template_name, data)
    return redirect('inventories:display_user')


@login_required()
def display_laptops(request):
    data = {}
    template_name = 'display_laptops.html'
    data['query'] = ''

    if 'l' in request.GET:
        # caso de busqueda
        data['query'] = request.GET.get('l')
        laptop_lists = Laptop.objects.filter(question_text__icontains=data['query'])

    else:
        # caso normal
        laptop_lists = Laptop.objects.all()

    page = request.GET.get('page', 1)
    paginator = Paginator(laptop_lists, 4)

    try:
        data['laptops'] = paginator.page(page)
    except PageNotAnInteger:
        data['laptops'] = paginator.page(1)
    except EmptyPage:
        data['laptops'] = paginator.page(paginator.num_pages)

    return render(request, template_name, data)


@login_required()
def display_desktops(request):
    data = {}
    template_name = 'display_desktops.html'

    data['query'] = ''
    if 'd' in request.GET:
        # caso de busqueda
        data['query'] = request.GET.get('d')
        desktop_lists = Desktop.objects.filter(question_text__icontains=data['query'])

    else:
        # caso normal
        desktop_lists = Desktop.objects.all()

    page = request.GET.get('page', 1)
    paginator = Paginator(desktop_lists, 4)

    try:
        data['desktops'] = paginator.page(page)
    except PageNotAnInteger:
        data['desktops'] = paginator.page(1)
    except EmptyPage:
        data['desktops'] = paginator.page(paginator.num_pages)

    return render(request, template_name, data)


@login_required()
def display_mobiles(request):
    data = {}
    template_name = 'display_mobiles.html'

    data['query'] = ''

    if 'm' in request.GET:
        # caso de busqueda
        data['query'] = request.GET.get('m')
        mobile_lists = Mobile.objects.filter(question_text__icontains=data['query'])

    else:
        # caso normal
        mobile_lists = Mobile.objects.all()

    page = request.GET.get('page', 1)
    paginator = Paginator(mobile_lists, 4)

    try:
        data['mobiles'] = paginator.page(page)
    except PageNotAnInteger:
        data['mobiles'] = paginator.page(1)
    except EmptyPage:
        data['mobiles'] = paginator.page(paginator.num_pages)

    return render(request, template_name, data)


@permission_required('inventories.add_desktop')
def create_desktop(request):
    data = {}
    template_name = 'create_desktop.html'

    data['form'] = DesktopForm(request.POST or None, request.FILES)

    if data['form'].is_valid():
        data['form'].save()
        return redirect('inventories:display_desktop')

    return render(request, template_name, data)


@permission_required('inventories.add_laptop')
def create_laptop(request):
    data = {}
    template_name = 'create_laptop.html'

    data['form'] = LaptopForm(request.POST or None, request.FILES)

    if data['form'].is_valid():
        data['form'].save()
        return redirect('inventories:display_laptop')

    return render(request, template_name, data)


@permission_required('inventories.add_mobile')
def create_mobile(request):
    data = {}
    template_name = 'create_mobile.html'

    data['form'] = MobileForm(request.POST or None, request.FILES)

    if data['form'].is_valid():
        data['form'].save()
        return redirect('inventories:display_mobile')

    return render(request, template_name, data)


@permission_required('inventories.change_desktop')
def update_desktop(request, id):
    template_name = 'update_desktop.html'
    data = {}

    desktop = Desktop.objects.get(pk=id)
    data['form'] = DesktopForm(request.POST or None, instance=desktop)

    if data['form'].is_valid():
        data['form'].save()
        return redirect('inventories:display_desktop')

    return render(request, template_name, data)


@permission_required('inventories.change_laptop')
def update_laptop(request, id):
    template_name = 'update_laptop.html'
    data = {}

    laptop = Laptop.objects.get(pk=id)
    data['form'] = LaptopForm(request.POST or None, instance=laptop)

    if data['form'].is_valid():
        data['form'].save()
        return redirect('inventories:display_laptop')

    return render(request, template_name, data)


@permission_required('inventories.change_mobile')
def update_mobile(request, id):
    template_name = 'update_mobile.html'
    data = {}

    mobile = Mobile.objects.get(pk=id)
    data['form'] = MobileForm(request.POST or None, instance=mobile)

    if data['form'].is_valid():
        data['form'].save()
        return redirect('inventories:display_mobile')

    return render(request, template_name, data)


@permission_required('inventories.delete_desktop')
def delete_desktop(request, id):
    # data = {}
    desktop = Desktop.objects.get(pk=id)
    # data['desktop'] = Desktop.objects.get(pk=id)
    # template_name = 'update_mobile.html'
    desktop.delete()
    # return render(request, template_name, data)
    return redirect('inventories:display_desktop')


@permission_required('inventories.delete_laptop')
def delete_laptop(request, id):
    # data = {}
    laptop = Laptop.objects.get(pk=id)
    # data['desktop'] = Desktop.objects.get(pk=id)
    # template_name = 'update_mobile.html'
    laptop.delete()
    # return render(request, template_name, data)
    return redirect('inventories:display_laptop')


@permission_required('inventories.delete_mobile')
def delete_mobile(request, id):
    # data = {}
    mobile = Mobile.objects.get(pk=id)
    # data['desktop'] = Desktop.objects.get(pk=id)
    # template_name = 'update_mobile.html'
    mobile.delete()
    # return render(request, template_name, data)
    return redirect('inventories:display_mobile')

inventories/templates/base.html
{% load static %}
{% include '_partials/_navbar.html' %}
<!DOCTYPE html>

<head>
<!-- Require meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://kit.fontawesome.com/6a748a1171.js" crossorigin="anonymous"></script>

    <!--
    <style>
      .breadcrumb{
              background: white;
              padding-left: 1;
              border-bottom: 1px solid black;
      }
      .breadcrumb a {
              color: black;
      }

    </style>
    -->
    <title>{% block title %}home{% endblock %}</title>
    {% block extra_css %}
    {% endblock %}

</head>
<body>


    {% block link %}{% endblock %}

    <div class="container">
    {% block content %}
        {% endblock %}

    </div>

    <!-- Optional JavaScript -->
    <!--  JQuery first, then Popper.js, the Bootsrap JS -->

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/98a2688348.js" crossorigin="anonymous"></script>
</body>

</html5>

inventories/templates/display_desktops.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

<html lang="es-cl">

    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <title>Lista de Desktops</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

    {% block extra_css %}
<style>
	.color_update_desktop {
		color: #009900;
		font-size: 22px;
	}
	.color_delete_desktop {
		color: #F51809;
		font-size: 18px;
	}
</style>
{% endblock %}


{% block content %}

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'inventories:index' %}"><i class="fas fa-home"></i></a></li>

        </ol>
    </nav>


<head>

    <div class="row mt-3">
        <div class="col-md-9 col-lg-10">
            <h3>Lista de Desktops</h3>
        </div>
    <div class="col-md-3 col-lg-2">
        {% if perms.inventories.add_desktop %}
        <a href="{% url 'inventories:create_desktop' %}" class="btn btn-success btn-block mt-3"><i class="fas fa-plus-square"></i> Agrega Desktop</a>

        {% endif %}
    </div>
    </div>
</head>
    <body>
    <table class="table table-hover mt-3">
    <thead>
      <tr>
        <th>id</th>
        <th>Model</th>
        <th>Price</th>
        <th>Status</th>
        <th>Issues</th>
        <th>Photo</th>
        <th></th>
      </tr>
    </thead>
    <tr>
    {% for item in desktops %}
        <tr>
            <td style="color: black">{{ item.id}}</td>
            <td style="color: black">{{ item.name }}</td>
            <td style="color: black">{{ item.price}}</td>
            <td style="color: black">{{ item.status }}</td>
            <td style="color: black">{{ item.issues }}</td>
            <td style="color: black"><img src="{{ item.photo.url }}" alt="" width="72" height="72"></td>
        <td>
            <div>

            </div>
            {% if perms.inventories.change_desktop %}
            <a href="{% url 'inventories:update_desktop' item.id %}"><i class="fas fa-edit color_update_desktop"></i></a>
            {% endif %}
            {% if perms.inventories.delete_desktop %}
            |
            <a href="{% url 'inventories:delete_desktop' item.id %}"><i class="fas fa-trash-alt color_delete_desktop"></i></a>
            {% endif %}
        </td>
        <tr>
    {% endfor %}
    </tr>
</table>
    {% if desktops.has_other_pages %}
      <ul class="pagination">
        {% if desktops.has_previous %}
          <li><a href="?page={{ desktops.previous_page_number }}">&laquo;</a></li>
        {% else %}
          <li class="disabled"><span>&laquo;</span></li>
        {% endif %}
        {% for i in desktops.paginator.page_range %}
          {% if desktops.number == i %}
            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
          {% else %}
            <li><a href="?page={{ i }}">{{ i }}</a></li>
          {% endif %}
        {% endfor %}
        {% if desktops.has_next %}
          <li><a href="?page={{ desktops.next_page_number }}">&raquo;</a></li>
        {% else %}
          <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
      </ul>
    {% endif %}
    </body>


<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    </html>
{% endblock %}

inventories/templates/display_laptops.html
{% extends 'base.html' %}
{% load bootstrap4 %}


<html lang="es-cl">

    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <title>Lista de </title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">


     {% block extra_css %}
<style>
	.color_update_laptop {
		color: #009900;
		font-size: 18px;
	}
	.color_delete_laptop{
		color: #F51809;
		font-size: 18px;
	}
</style>
{% endblock %}

{% block content %}

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'inventories:index' %}"><i class="fas fa-home"></i></a></li>

        </ol>
    </nav>

<head>

    <div class="row mt-3">
        <div class="col-md-9 col-lg-10">
            <h3>Lista de Laptops</h3>
        </div>
    <div class="col-md-3 col-lg-2">
        {% if perms.inventories.add_laptop %}
        <a href="{% url 'inventories:create_laptop' %}" class="btn btn-success btn-block mt-3"><i class="fas fa-plus-square"></i> Agrega Laptop</a>
        {% endif %}
    </div>
    </div>
</head>
    <button type="button" class="btn btn-default">Default</button>
    <body>
    <table class="table table-hover mt-3">
    <thead>
      <tr>
        <th>id</th>
        <th>Model</th>
        <th>Price</th>
        <th>Status</th>
        <th>Issues</th>
        <th>Photos</th>
      </tr>
    </thead>
    <tr>
    {% for item in laptops %}
        <tr>
            <td style="color: black">{{ item.id}}</td>
            <td style="color: black">{{ item.name }}</td>
            <td style="color: black">{{ item.price}}</td>
            <td style="color: black">{{ item.status }}</td>
            <td style="color: black">{{ item.issues }}</td>
            <td style="color: black"><img src="{{ item.photo.url }}" alt="" width="72" height="72"></td>
        <td>
            {% if perms.inventories.change_laptop %}
            <a href="{% url 'inventories:update_laptop' item.id %}"><i class="fas fa-edit color_update_laptop"></i></a>
            {% endif %}
            {% if perms.inventories.delete_laptop %}
            |
            <a href="{% url 'inventories:delete_laptop' item.id %}"><i class="fas fa-trash-alt color_delete_laptop"></i></a>
            {% endif %}
        </td>
        <tr>
    {% endfor %}
    </tr>
</table>

    {% if laptops.has_other_pages %}
      <ul class="pagination">
        {% if laptops.has_previous %}
          <li><a href="?page={{ laptops.previous_page_number }}">&laquo;</a></li>
        {% else %}
          <li class="disabled"><span>&laquo;</span></li>
        {% endif %}
        {% for i in laptops.paginator.page_range %}
          {% if laptops.number == i %}
            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
          {% else %}
            <li><a href="?page={{ i }}">{{ i }}</a></li>
          {% endif %}
        {% endfor %}
        {% if laptops.has_next %}
          <li><a href="?page={{ laptops.next_page_number }}">&raquo;</a></li>
        {% else %}
          <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
      </ul>
    {% endif %}
    </body>



<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    </html>
{% endblock %}

inventories/templates/display_mobiles.html
{% extends 'base.html' %}
{% load bootstrap4 %}

<html lang="es-cl">

    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <title>Lista de mobiles</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

    {% block extra_css %}
<style>
	.color_update_mobile {
		color: #009900;
		font-size: 18px;
	}
	.color_delete_mobile {
		color: #F51809;
		font-size: 18px;
	}
</style>
{% endblock %}


{% block content %}

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'inventories:index' %}"><i class="fas fa-home"></i></a></li>

        </ol>
    </nav>


<head>

    <div class="row mt-3">
        <div class="col-md-9 col-lg-10">
            <h3>Lista de Mobiles</h3>
        </div>
    <div class="col-md-3 col-lg-2">
        {% if perms.inventories.add_mobile %}
        <a href="{% url 'inventories:create_mobile' %}" class="btn btn-success btn-block mt-3"><i class="fas fa-plus-square"></i> Agrega Mobile</a>
        {% endif %}
    </div>
    </div>
</head>
    <body>
    <table class="table table-hover mt-3">
    <thead>
      <tr>
        <th>id</th>
        <th>Model</th>
        <th>Price</th>
        <th>Status</th>
        <th>Issues</th>
        <th>Photos</th>
      </tr>
    </thead>
    <tr>
    {% for item in mobiles %}
        <tr>
            <td style="color: black">{{ item.id}}</td>
            <td style="color: black">{{ item.name }}</td>
            <td style="color: black">{{ item.price}}</td>
            <td style="color: black">{{ item.status }}</td>
            <td style="color: black">{{ item.issues }}</td>
            <td style="color: black"><img src="{{ item.photo.url }}" alt="" width="72" height="72"></td>
        <td>
            {% if perms.inventories.change_mobile %}
            <a href="{% url 'inventories:update_mobile' item.id %}"><i class="fas fa-edit color_update_mobile"></i></a>
            {% endif %}
            {% if perms.inventories.delete_mobile %}
            |
            <a href="{% url 'inventories:delete_mobile' item.id %}"><i class="fas fa-trash-alt color_delete_mobile"></i></a>
            {% endif %}
        </td>
        <tr>
    {% endfor %}
    </tr>
</table>
    {% if mobiles.has_other_pages %}
      <ul class="pagination">
        {% if mobiles.has_previous %}
          <li><a href="?page={{ mobiles.previous_page_number }}">&laquo;</a></li>
        {% else %}
          <li class="disabled"><span>&laquo;</span></li>
        {% endif %}
        {% for i in mobiles.paginator.page_range %}
          {% if mobiles.number == i %}
            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
          {% else %}
            <li><a href="?page={{ i }}">{{ i }}</a></li>
          {% endif %}
        {% endfor %}
        {% if mobiles.has_next %}
          <li><a href="?page={{ mobiles.next_page_number }}">&raquo;</a></li>
        {% else %}
          <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
      </ul>
    {% endif %}
    </body>


<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    </html>
{% endblock %}